train:
    sup:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_speech.SpeechSpeechDataset
            dataset_conf:
                feat_type: feat
                src_data: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_mel_f80/train/feat.scp
                tgt_label: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_raw_fft2048/train/feat.scp

            shuffle: True
            is_descending: True
            batches_per_epoch: 200
            batch_frames: 30000 #1000000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            data_len: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_mel_f80/train/feat_len.scp


valid:
    dev:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_speech.SpeechSpeechDataset
            dataset_conf:
                feat_type: feat
                src_data: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_mel_f80/valid/feat.scp
                tgt_label: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_raw_fft2048/valid/feat.scp

            shuffle: False
            is_descending: True
            batch_frames: 30000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            data_len: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_mel_f80/valid/feat_len.scp


test:
    clean:
        type: piece.PieceIterator
        conf:
            dataset_type: speech.speech_speech.SpeechSpeechDataset
            dataset_conf:
                feat_type: feat
                src_data: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_mel_f80/test/feat.scp
                tgt_label: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_raw_fft2048/test/feat.scp

            shuffle: False
            batch_size: 1
            data_len: /project/nakamura-lab05/Work/novitasari-s/tools/SpeeChain/datasets/speech_text/ljspeech/data/taco_mel_f80/test/feat_len.scp

   
